# Authentication
ssh-add -A > /dev/null 2>&1

# Colours
export GREP_OPTIONS='--color=auto'
if [ $(command -v src-hilite-lesspipe.sh) ]; then
  # Requires source-highlight install
  export LESSOPEN="| src-hilite-lesspipe.sh %s"
  export LESS=' -R '
fi
alias ls='ls -G'
alias tree="tree -C"

# Bash autocomplete support
source ~/.git-completion.bash

# Prompt
source ~/.git-prompt.sh
export PS1='\h:\W \u$(__git_ps1 " (%s)")$'

# Shortcuts
alias path='echo $PATH | tr ":" "\n"'
alias ll='ls -lh'
alias l='tree -L 1'
alias slime='"/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"'
alias dirs='dirs -v'

# Environment Modules
if [ $(command -v /usr/local/Cellar/modules/3.2.10/Modules/bin/modulecmd) ]; then
  # Assuming installation via Brew (and so not on the PATH), if installed at all
  source /usr/local/Cellar/modules/3.2.10/Modules/init/bash
fi

# Git shortcuts
if [ -f ~/.git_shortcuts ]; then
  source ~/.git_shortcuts
fi

# XMOS toolchain
if [ -f ~/.xmos_tools ]; then
  source ~/.xmos_tools
fi

# Phabricator
if [ -d ~/.phabricator ]; then
  export PATH=~/.phabricator/arcanist/bin:$PATH
  source ~/.phabricator/arcanist/resources/shell/bash-completion
fi
