" Enable mouse support
set mouse=a

" Dectect the type of file that is being editied
filetype on

" Treat XC files as if they're C
au BufRead,BufNewFile *.xc set filetype=c

" Show syntax highlighting
syntax on

" Show line numbers
set number

" Highlight characters that go over 80 columns (by drawing a border on the 81st)
set colorcolumn=81
highlight ColorColumn ctermbg=lightgrey

" Handle binary files using xxd
augroup Binary
au!
au BufReadPre *.bin let &bin=1
au BufReadPost *.bin if &bin | %!xxd
au BufReadPost *.bin set ft=xxd | endif
au BufWritePre *.bin if &bin | %!xxd -r
au BufWritePre *.bin endif
au BufWritePost *.bin if &bin | %!xxd
au BufWritePost *.bin set nomod | endif
augroup END
